"""empty message

Revision ID: 298e2badbdea
Revises: 
Create Date: 2019-04-23 12:13:19.286000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298e2badbdea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=60), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group')
    )
    op.create_index(op.f('ix_groups_entry_date'), 'groups', ['entry_date'], unique=False)
    op.create_table('partnership_arms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partnership_arm', sa.String(length=100), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partnership_arms_entry_date'), 'partnership_arms', ['entry_date'], unique=False)
    op.create_table('pcfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pcf', sa.String(length=60), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcfs_entry_date'), 'pcfs', ['entry_date'], unique=False)
    op.create_table('staff_roles',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_index(op.f('ix_staff_roles_entry_date'), 'staff_roles', ['entry_date'], unique=False)
    op.create_table('cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pcf_id', sa.Integer(), nullable=True),
    sa.Column('cell', sa.String(length=60), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pcf_id'], ['pcfs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cells_entry_date'), 'cells', ['entry_date'], unique=False)
    op.create_table('churches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('church', sa.String(length=60), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_churches_entry_date'), 'churches', ['entry_date'], unique=False)
    op.create_table('staffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.String(length=5), nullable=True),
    sa.Column('f_name', sa.String(length=60), nullable=False),
    sa.Column('l_name', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['staff_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staffs_email'), 'staffs', ['email'], unique=False)
    op.create_index(op.f('ix_staffs_entry_date'), 'staffs', ['entry_date'], unique=False)
    op.create_index(op.f('ix_staffs_f_name'), 'staffs', ['f_name'], unique=False)
    op.create_index(op.f('ix_staffs_l_name'), 'staffs', ['l_name'], unique=False)
    op.create_index(op.f('ix_staffs_phone'), 'staffs', ['phone'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=True),
    sa.Column('cell_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('l_name', sa.String(length=60), nullable=False),
    sa.Column('f_name', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('kingschat_no', sa.String(length=60), nullable=True),
    sa.Column('birthday', sa.String(length=60), nullable=True),
    sa.Column('w_anniversary', sa.String(length=60), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=False)
    op.create_index(op.f('ix_members_entry_date'), 'members', ['entry_date'], unique=False)
    op.create_index(op.f('ix_members_f_name'), 'members', ['f_name'], unique=False)
    op.create_index(op.f('ix_members_l_name'), 'members', ['l_name'], unique=False)
    op.create_index(op.f('ix_members_phone'), 'members', ['phone'], unique=False)
    op.create_table('partner_givings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('arm_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_pledge', sa.Boolean(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['arm_id'], ['partnership_arms.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tithe_givings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tithe_givings_entry_date'), 'tithe_givings', ['entry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tithe_givings_entry_date'), table_name='tithe_givings')
    op.drop_table('tithe_givings')
    op.drop_table('partner_givings')
    op.drop_index(op.f('ix_members_phone'), table_name='members')
    op.drop_index(op.f('ix_members_l_name'), table_name='members')
    op.drop_index(op.f('ix_members_f_name'), table_name='members')
    op.drop_index(op.f('ix_members_entry_date'), table_name='members')
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_staffs_phone'), table_name='staffs')
    op.drop_index(op.f('ix_staffs_l_name'), table_name='staffs')
    op.drop_index(op.f('ix_staffs_f_name'), table_name='staffs')
    op.drop_index(op.f('ix_staffs_entry_date'), table_name='staffs')
    op.drop_index(op.f('ix_staffs_email'), table_name='staffs')
    op.drop_table('staffs')
    op.drop_index(op.f('ix_churches_entry_date'), table_name='churches')
    op.drop_table('churches')
    op.drop_index(op.f('ix_cells_entry_date'), table_name='cells')
    op.drop_table('cells')
    op.drop_index(op.f('ix_staff_roles_entry_date'), table_name='staff_roles')
    op.drop_table('staff_roles')
    op.drop_index(op.f('ix_pcfs_entry_date'), table_name='pcfs')
    op.drop_table('pcfs')
    op.drop_index(op.f('ix_partnership_arms_entry_date'), table_name='partnership_arms')
    op.drop_table('partnership_arms')
    op.drop_index(op.f('ix_groups_entry_date'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
